### ISSUE TITLE
Problem in _raw_split

### ISSUE THREAD

**Issue by bedna-KU** [Bystroushaak/abclinuxuapi#13]
```
import urllib3
import dhtmlparser as d

http = urllib3.PoolManager ()
r = http.request ('GET', 'https://linuxos.sk/profil/13656/prispevky/komentare/')

if r.status == 200:
	dom = d.parseString (r.data)
	print (dom)
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    dom = d.parseString (r.data)
  File "/home/mario/.local/lib/python3.8/site-packages/dhtmlparser/__init__.py", line 267, in parseString
    HTMLElement(x) for x in _raw_split(txt)
  File "/home/mario/.local/lib/python3.8/site-packages/dhtmlparser/__init__.py", line 94, in _raw_split
    content += c
TypeError: can only concatenate str (not "int") to str

**Comment by Bystroushaak** [comment]
Closing as it was already solved in the correct repository: https://github.com/Bystroushaak/pyDHTMLParser/issues/27
